#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ] || [ "$branch" = "dev" ]; then
  echo -e "👮🚨🚔🚔🚔🚓🚓🚨 No puedes realizar un commit directo a la rama \"$branch\""
  exit 1
fi

# Check tsconfig standards
# npm run check-types ||
# (
#     echo -e "\nTienes errores de tipado. Realiza los cambios requeridos 👆"
#     false;
# )


npx lint-staged
